// The only place user-facing words live. Every key must exist in both `en` and `th`
// (strings.test.ts enforces it). Character names (Rex, Sam, ...) stay the same in both languages.

const en: Record<string, string> = {
  text: '{text}',

  // ----- HUD / static UI -----
  'hud.start': 'Start job',
  'hud.running': 'Job running...',
  'hud.menu': 'Menu',
  'hud.noJob': 'No active job — press Start or click Rex',
  'hud.briefing': 'Talking to Rex about the order...',
  'steps.aria': 'Workflow progress',
  'canvas.aria': 'Pixel office',
  'drawer.aria': 'Controls and details',
  'controls.title': 'Controls',
  'lang.label': 'LANGUAGE',
  'lang.aria': 'Language',
  'lang.en': 'English',
  'lang.th': 'ไทย',
  'btn.reset': 'Reset',
  'auto.answer': 'Auto-answer',
  'speed.label': 'SPEED',
  'speed.aria': 'Simulation speed',
  'view.label': 'VIEW',
  'view.aria': 'Camera',
  'view.zoomOut.title': 'Zoom out (-)',
  'view.zoomIn.title': 'Zoom in (+ or mouse wheel)',
  'view.fit': 'Fit',
  'view.fit.title': 'See the whole building (0)',
  'view.hint': 'Zoom in, then look around: mouse to the screen edge, WASD / arrow keys, or drag.',
  'try.label': 'TRY',
  'try.reject': 'QA reject',
  'try.reject.title': 'The next QA review sends the work back once',
  'try.error': 'Agent error',
  'try.error.title': 'Crash a working staff member',
  'try.jam': 'Courier jam',
  'try.jam.title': 'Drop several memos on the courier',
  'queue.title': 'Courier queue',
  'queue.carrying': 'Carrying: {label}',
  'queue.empty': 'Queue is empty',
  'feed.title': 'Event feed',
  'credit.font': 'Thai font: Silver by Poppy Works (CC BY 4.0)',
  'dlg.send': 'Send',
  'dlg.placeholder': 'Type your answer...',

  // ----- inspector -----
  'inspector.title': 'Inspector',
  'inspector.hint': 'Click a character to see what they are doing and their conversations.',
  'inspector.doing': 'Doing',
  'inspector.model': 'Model',
  'inspector.convos': 'Conversations',
  'inspector.noConvos': 'No conversations yet',
  'inspector.inbox': 'Inbox {n}',
  'inspector.carrying': 'Carrying {label}',
  'model.queue': 'queue (plain code, no AI)',
  you: 'You',

  // ----- workflow steps / activities -----
  'step.idle': 'Idle',
  'step.brief': 'Brief',
  'step.approval': 'Approve',
  'step.meeting': 'Meeting',
  'step.team': 'Team',
  'step.work': 'Work',
  'step.review': 'Review',
  'step.delivery': 'Deliver',
  'step.done': 'Done',
  'act.idle': 'Idle',
  'act.typing': 'Working',
  'act.thinking': 'Thinking',
  'act.talking': 'Talking',
  'act.reviewing': 'Reviewing',
  'act.waiting': 'Waiting',
  'act.break': 'Coffee break',
  'act.error': 'Error!',
  'act.celebrate': 'Celebrating',

  // ----- roster -----
  'role.owner': 'Owner',
  'role.secretary': 'Secretary',
  'role.research-head': 'Head of Research',
  'role.research-1': 'Researcher',
  'role.research-2': 'Researcher',
  'role.prod-head': 'Head of Production',
  'role.prod-1': 'Producer',
  'role.prod-2': 'Producer',
  'role.qa': 'QA Reviewer',
  'role.courier': 'Courier',
  'blurb.owner': 'Takes your order, gathers requirements and decides which departments to involve.',
  'blurb.secretary': 'Writes the brief and delivers the final result to the client.',
  'blurb.research-head': 'Splits the research work, reviews findings and reports to Production.',
  'blurb.research-1': 'Gathers facts and sources.',
  'blurb.research-2': 'Gathers facts and sources.',
  'blurb.prod-head': 'Plans the build, merges research into the deliverable and fixes QA findings.',
  'blurb.prod-1': 'Drafts and builds parts of the deliverable.',
  'blurb.prod-2': 'Drafts and builds parts of the deliverable.',
  'blurb.qa': 'Checks the deliverable against the approved brief and can send it back.',
  'blurb.courier': 'A real first-in-first-out queue: carries documents between desks. Not an AI.',

  // ----- event feed -----
  'feed.reset': 'Office reset',
  'feed.job': 'New job: {title}',
  'feed.stage': 'Stage: {stage}',
  'feed.jobDone': 'Job complete',
  'feed.queued': 'Queued "{label}" {from} > {to}',
  'feed.delivered': 'Delivered "{label}" to {to}',
  'feed.handed': '{from} handed "{label}" to {to}',
  'feed.filed': 'Deliverable filed in the archive',
  'feed.pass': 'QA passed (round {round})',
  'feed.reject': 'QA rejected (round {round}): {reason}',
  'feed.error': '{name} hit an error',

  // ----- documents carried by the courier -----
  'doc.briefDraft': 'Brief draft',
  'doc.memo': 'Memo',
  'doc.findings': 'Findings',
  'doc.researchReport': 'Research report',
  'doc.briefResearch': 'Brief + research',
  'doc.draftPart': 'Draft part',
  'doc.deliverable': 'Deliverable v{version}',
  'doc.deliverableShort': 'Deliverable',
  'doc.reviewNotes': 'Review notes',
  'doc.fixList': 'Fix list',
  'doc.fixedDraft': 'Fixed draft',
  'doc.approved': 'Approved package',
  'doc.changeRequest': 'Change request',

  // ----- what agents are doing (activity notes) -----
  'note.writeBrief': 'Writing the brief',
  'note.updateBrief': 'Updating the brief',
  'note.coffee': 'Coffee break',
  'note.restroom': 'Restroom',
  'note.crashed': 'Tool crashed',
  'note.toServer': 'Heading to the server room',
  'note.restarting': 'Restarting the tool server',
  'note.gathering': 'Gathering facts',
  'note.outline': 'Drafting the outline',
  'note.coffeeWait': 'Coffee while waiting for the research',
  'note.readFindings': 'Reading the findings',
  'note.writeReport': 'Writing the research report',
  'note.planMerge': 'Planning the merge',
  'note.merging': 'Merging into the draft',
  'note.assembling': 'Assembling the deliverable',
  'note.checking': 'Checking against the brief',
  'note.readNotes': 'Reading the review notes',
  'note.fixing': 'Fixing the issues',
  'note.reassembling': 'Re-assembling the deliverable',
  'note.rechecking': 'Re-checking the changes',
  'note.packaging': 'Packaging the result',
  'note.filing': 'Filing the deliverable',

  // ----- chat: the owner takes the order -----
  'ask.idea': 'Welcome to the office! What would you like us to produce?',
  'ask.idea.ph': 'e.g. A weekly market newsletter',
  'auto.idea': 'A weekly market newsletter',
  'ask.audience': '"{title}" - sounds good. Who is it for, and what tone should it have?',
  'ask.audience.ph': 'e.g. Beginners, friendly tone',
  'auto.audience': 'Beginners, friendly tone',
  'ask.limits': 'Any hard limits? Length, format, deadline...',
  'ask.limits.ph': 'or type your own',
  'choice.none': 'No limits',
  'choice.onePage': 'One page',
  'choice.detailed': 'Detailed report',
  'choice.approve': 'Approve',
  'choice.revise': 'Revise',
  'choice.accept': 'Accept',
  'choice.requestChanges': 'Request changes',
  'ask.approve': 'Here is the brief:\n{details}\n\nShall we start?',
  'ask.approve.ph': 'or type a change',
  'ask.reviseWhat': 'What should I change?',
  'ask.reviseWhat.ph': 'tell me what to change',
  'brief.body': 'Goal: {goal}\nAudience & tone: {audience}\nLimits: {limits}{changes}',
  'brief.change': '{prev}\nChange: {text}',

  // ----- scripted conversations -----
  'say.writeBrief': 'Sam, please write this up as a brief.',
  'say.meetOwner': 'New job: {title}. We need Research and Production, then QA.',
  'say.meetResearch': 'Research will gather the facts first.',
  'say.meetProd': 'Production drafts in parallel and merges the facts when they arrive.',
  'say.meetOwner2': 'Perfect. Keep me posted.',
  'say.huddleResearch': 'Leo, Mina: collect facts and sources for the brief.',
  'say.huddleLeo': 'On it. I will take the market data.',
  'say.huddleMina': 'I will cover background and sources.',
  'say.huddleProd': 'Kai, Zoe: start the outline now, merge the research once it lands.',
  'say.huddleKai': 'I will draft the structure.',
  'say.huddleZoe': 'And I will prepare the visuals.',
  'say.celebrate': 'Great job, team! Another one delivered.',
  'say.qaPass': 'Looks good. Approved!',
  'say.qaReject': '{reason}. Please fix and resubmit.',
  'say.filing': 'Wonderful. I will file it in the archive.',
  'say.changeNoted': 'Change request noted: {change}',
  'say.crash': 'My tool just crashed!',
  'say.restartPlan': 'I will restart it from the server room.',
  'say.restarting': 'Restarting the tool server...',
  'say.restarted': 'Restarted. Please retry.',
  'say.recovered': 'Working again, thanks!',

  // ----- QA verdict reasons -----
  'reason.matches': 'Matches the brief',
  'reason.noSources': 'Section 2 has no sources',
  'reason.applied': 'Changes applied',

  // ----- delivery -----
  'ask.deliver':
    'Your deliverable is ready: "{title}".\n\n(Demo output - a real run would show the actual result here.)\n\nDo you accept it?',
  'ask.deliver.ph': 'or describe what to change',
  'ask.changeWhat': 'What should we change?',
  'ask.changeWhat.ph': 'tell me what to change',
};

const th: Record<string, string> = {
  text: '{text}',

  'hud.start': 'เริ่มงาน',
  'hud.running': 'กำลังทำงาน...',
  'hud.menu': 'เมนู',
  'hud.noJob': 'ยังไม่มีงาน — กด "เริ่มงาน" หรือคลิกที่ Rex',
  'hud.briefing': 'กำลังคุยกับ Rex เรื่องคำสั่งงาน...',
  'steps.aria': 'ความคืบหน้าของงาน',
  'canvas.aria': 'ออฟฟิศพิกเซล',
  'drawer.aria': 'ปุ่มควบคุมและรายละเอียด',
  'controls.title': 'ควบคุม',
  'lang.label': 'ภาษา',
  'lang.aria': 'ภาษา',
  'lang.en': 'English',
  'lang.th': 'ไทย',
  'btn.reset': 'รีเซ็ต',
  'auto.answer': 'ตอบอัตโนมัติ',
  'speed.label': 'ความเร็ว',
  'speed.aria': 'ความเร็วการจำลอง',
  'view.label': 'มุมมอง',
  'view.aria': 'กล้อง',
  'view.zoomOut.title': 'ซูมออก (-)',
  'view.zoomIn.title': 'ซูมเข้า (+ หรือลูกกลิ้งเมาส์)',
  'view.fit': 'พอดีจอ',
  'view.fit.title': 'ดูทั้งตึก (0)',
  'view.hint': 'ซูมเข้าแล้วเลื่อนดูได้: เมาส์ชิดขอบจอ, WASD / ปุ่มลูกศร หรือลากเมาส์',
  'try.label': 'ทดลอง',
  'try.reject': 'QA ตีกลับ',
  'try.reject.title': 'การตรวจ QA ครั้งถัดไป จะตีงานกลับ 1 ครั้ง',
  'try.error': 'เอเจนต์ขัดข้อง',
  'try.error.title': 'ทำให้พนักงานที่กำลังทำงานขัดข้อง',
  'try.jam': 'คิวคูเรียร์ล้น',
  'try.jam.title': 'โยนบันทึกหลายฉบับให้คูเรียร์',
  'queue.title': 'คิวคูเรียร์',
  'queue.carrying': 'กำลังถือ: {label}',
  'queue.empty': 'คิวว่าง',
  'feed.title': 'ฟีดเหตุการณ์',
  'credit.font': 'ฟอนต์ไทย: Silver โดย Poppy Works (CC BY 4.0)',
  'dlg.send': 'ส่ง',
  'dlg.placeholder': 'พิมพ์คำตอบ...',

  'inspector.title': 'ข้อมูลตัวละคร',
  'inspector.hint': 'คลิกตัวละคร เพื่อดูว่ากำลังทำอะไร และบทสนทนาของเขา',
  'inspector.doing': 'กำลังทำ',
  'inspector.model': 'โมเดล',
  'inspector.convos': 'บทสนทนา',
  'inspector.noConvos': 'ยังไม่มีบทสนทนา',
  'inspector.inbox': 'กล่องเข้า {n}',
  'inspector.carrying': 'ถือ {label}',
  'model.queue': 'คิว (โค้ดธรรมดา ไม่ใช่ AI)',
  you: 'คุณ',

  'step.idle': 'ว่าง',
  'step.brief': 'รับบรีฟ',
  'step.approval': 'อนุมัติ',
  'step.meeting': 'ประชุม',
  'step.team': 'ทีม',
  'step.work': 'ทำงาน',
  'step.review': 'ตรวจ',
  'step.delivery': 'ส่งมอบ',
  'step.done': 'เสร็จ',
  'act.idle': 'ว่าง',
  'act.typing': 'กำลังทำงาน',
  'act.thinking': 'กำลังคิด',
  'act.talking': 'กำลังคุย',
  'act.reviewing': 'กำลังตรวจ',
  'act.waiting': 'รอ',
  'act.break': 'พักกาแฟ',
  'act.error': 'ขัดข้อง!',
  'act.celebrate': 'กำลังฉลอง',

  'role.owner': 'เจ้าของบริษัท',
  'role.secretary': 'เลขา',
  'role.research-head': 'หัวหน้าฝ่ายวิจัย',
  'role.research-1': 'นักวิจัย',
  'role.research-2': 'นักวิจัย',
  'role.prod-head': 'หัวหน้าฝ่ายผลิต',
  'role.prod-1': 'ผู้ผลิตงาน',
  'role.prod-2': 'ผู้ผลิตงาน',
  'role.qa': 'ผู้ตรวจ QA',
  'role.courier': 'คูเรียร์',
  'blurb.owner': 'รับคำสั่งงานจากคุณ เก็บความต้องการ และเลือกว่าจะใช้แผนกไหนบ้าง',
  'blurb.secretary': 'เขียนบรีฟ และส่งมอบผลงานสุดท้ายให้ลูกค้า',
  'blurb.research-head': 'แบ่งงานวิจัย ตรวจผลที่ได้ แล้วรายงานให้ฝ่ายผลิต',
  'blurb.research-1': 'รวบรวมข้อเท็จจริงและแหล่งที่มา',
  'blurb.research-2': 'รวบรวมข้อเท็จจริงและแหล่งที่มา',
  'blurb.prod-head': 'วางแผนการผลิต รวมงานวิจัยเข้าไปในผลงาน และแก้ตามที่ QA พบ',
  'blurb.prod-1': 'ร่างและสร้างส่วนต่างๆ ของผลงาน',
  'blurb.prod-2': 'ร่างและสร้างส่วนต่างๆ ของผลงาน',
  'blurb.qa': 'ตรวจผลงานเทียบกับบรีฟที่อนุมัติแล้ว และตีกลับได้',
  'blurb.courier': 'คิวเข้าก่อนออกก่อนจริงๆ: ถือเอกสารส่งระหว่างโต๊ะ ไม่ใช่ AI',

  'feed.reset': 'รีเซ็ตออฟฟิศ',
  'feed.job': 'งานใหม่: {title}',
  'feed.stage': 'ขั้นตอน: {stage}',
  'feed.jobDone': 'งานเสร็จสมบูรณ์',
  'feed.queued': 'เข้าคิว "{label}" {from} > {to}',
  'feed.delivered': 'ส่ง "{label}" ถึง {to} แล้ว',
  'feed.handed': '{from} ยื่น "{label}" ให้ {to}',
  'feed.filed': 'เก็บผลงานเข้าห้องเอกสารแล้ว',
  'feed.pass': 'QA ผ่าน (รอบที่ {round})',
  'feed.reject': 'QA ตีกลับ (รอบที่ {round}): {reason}',
  'feed.error': '{name} ขัดข้อง',

  'doc.briefDraft': 'ร่างบรีฟ',
  'doc.memo': 'บันทึกข้อความ',
  'doc.findings': 'ผลการค้นคว้า',
  'doc.researchReport': 'รายงานวิจัย',
  'doc.briefResearch': 'บรีฟ + งานวิจัย',
  'doc.draftPart': 'ส่วนของร่างงาน',
  'doc.deliverable': 'ผลงาน v{version}',
  'doc.deliverableShort': 'ผลงาน',
  'doc.reviewNotes': 'บันทึกการตรวจ',
  'doc.fixList': 'รายการที่ต้องแก้',
  'doc.fixedDraft': 'ร่างที่แก้แล้ว',
  'doc.approved': 'ชุดงานที่อนุมัติแล้ว',
  'doc.changeRequest': 'คำขอแก้ไข',

  'note.writeBrief': 'กำลังเขียนบรีฟ',
  'note.updateBrief': 'กำลังปรับบรีฟ',
  'note.coffee': 'พักกาแฟ',
  'note.restroom': 'ห้องน้ำ',
  'note.crashed': 'เครื่องมือล่ม',
  'note.toServer': 'กำลังไปห้องเซิร์ฟเวอร์',
  'note.restarting': 'กำลังรีสตาร์ตเซิร์ฟเวอร์เครื่องมือ',
  'note.gathering': 'กำลังรวบรวมข้อเท็จจริง',
  'note.outline': 'กำลังร่างโครงเรื่อง',
  'note.coffeeWait': 'พักกาแฟระหว่างรอผลวิจัย',
  'note.readFindings': 'กำลังอ่านผลการค้นคว้า',
  'note.writeReport': 'กำลังเขียนรายงานวิจัย',
  'note.planMerge': 'กำลังวางแผนรวมงาน',
  'note.merging': 'กำลังรวมเข้ากับร่างงาน',
  'note.assembling': 'กำลังประกอบผลงาน',
  'note.checking': 'กำลังตรวจเทียบกับบรีฟ',
  'note.readNotes': 'กำลังอ่านบันทึกการตรวจ',
  'note.fixing': 'กำลังแก้ไขปัญหา',
  'note.reassembling': 'กำลังประกอบผลงานใหม่',
  'note.rechecking': 'กำลังตรวจส่วนที่แก้อีกครั้ง',
  'note.packaging': 'กำลังจัดชุดผลงาน',
  'note.filing': 'กำลังเก็บผลงานเข้าแฟ้ม',

  'ask.idea': 'ยินดีต้อนรับสู่ออฟฟิศ! อยากให้เราผลิตอะไรดี?',
  'ask.idea.ph': 'เช่น จดหมายข่าวตลาดรายสัปดาห์',
  'auto.idea': 'จดหมายข่าวตลาดรายสัปดาห์',
  'ask.audience': '"{title}" - น่าสนใจ ใครคือผู้อ่าน และอยากได้โทนแบบไหน?',
  'ask.audience.ph': 'เช่น มือใหม่ โทนเป็นกันเอง',
  'auto.audience': 'มือใหม่ โทนเป็นกันเอง',
  'ask.limits': 'มีข้อจำกัดตายตัวไหม? ความยาว รูปแบบ กำหนดส่ง...',
  'ask.limits.ph': 'หรือพิมพ์เอง',
  'choice.none': 'ไม่มีข้อจำกัด',
  'choice.onePage': 'หน้าเดียว',
  'choice.detailed': 'รายงานละเอียด',
  'choice.approve': 'อนุมัติ',
  'choice.revise': 'ขอแก้ไข',
  'choice.accept': 'ยอมรับ',
  'choice.requestChanges': 'ขอให้แก้ไข',
  'ask.approve': 'นี่คือบรีฟ:\n{details}\n\nเริ่มเลยไหม?',
  'ask.approve.ph': 'หรือพิมพ์สิ่งที่อยากแก้',
  'ask.reviseWhat': 'ให้แก้อะไรดี?',
  'ask.reviseWhat.ph': 'บอกได้เลยว่าจะให้แก้อะไร',
  'brief.body': 'เป้าหมาย: {goal}\nผู้อ่านและโทน: {audience}\nข้อจำกัด: {limits}{changes}',
  'brief.change': '{prev}\nแก้ไข: {text}',

  'say.writeBrief': 'Sam ช่วยเรียบเรียงเรื่องนี้เป็นบรีฟหน่อย',
  'say.meetOwner': 'งานใหม่: {title} — เราต้องใช้ฝ่ายวิจัยกับฝ่ายผลิต แล้วตามด้วย QA',
  'say.meetResearch': 'ฝ่ายวิจัยจะรวบรวมข้อเท็จจริงก่อน',
  'say.meetProd': 'ฝ่ายผลิตจะร่างงานควบคู่กันไป แล้วรวมข้อมูลเมื่อได้รับ',
  'say.meetOwner2': 'เยี่ยม คอยรายงานด้วยนะ',
  'say.huddleResearch': 'Leo, Mina: ช่วยรวบรวมข้อเท็จจริงและแหล่งที่มา สำหรับบรีฟ',
  'say.huddleLeo': 'รับทราบ ผมจะดูข้อมูลตลาดเอง',
  'say.huddleMina': 'ฉันจะดูข้อมูลพื้นหลังและแหล่งอ้างอิง',
  'say.huddleProd': 'Kai, Zoe: เริ่มวางโครงเรื่องเลย แล้วรวมงานวิจัยเมื่อมาถึง',
  'say.huddleKai': 'ผมจะร่างโครงสร้าง',
  'say.huddleZoe': 'ส่วนฉันจะเตรียมภาพประกอบ',
  'say.celebrate': 'เก่งมากทุกคน! ส่งมอบได้อีกหนึ่งงาน',
  'say.qaPass': 'ดูดีเลย อนุมัติ!',
  'say.qaReject': '{reason} กรุณาแก้ แล้วส่งใหม่',
  'say.filing': 'ยอดเยี่ยม เดี๋ยวฉันเก็บเข้าห้องเอกสารนะ',
  'say.changeNoted': 'รับคำขอแก้ไขแล้ว: {change}',
  'say.crash': 'เครื่องมือเพิ่งล่ม!',
  'say.restartPlan': 'เดี๋ยวฉันไปรีสตาร์ตที่ห้องเซิร์ฟเวอร์เอง',
  'say.restarting': 'กำลังรีสตาร์ตเซิร์ฟเวอร์เครื่องมือ...',
  'say.restarted': 'รีสตาร์ตแล้ว ลองใหม่ได้เลย',
  'say.recovered': 'กลับมาทำงานได้แล้ว ขอบคุณ!',

  'reason.matches': 'ตรงตามบรีฟ',
  'reason.noSources': 'หัวข้อที่ 2 ไม่มีแหล่งอ้างอิง',
  'reason.applied': 'แก้ไขตามที่ขอแล้ว',

  'ask.deliver':
    'ผลงานของคุณพร้อมแล้ว: "{title}"\n\n(นี่คือผลลัพธ์ตัวอย่าง — การรันจริง จะแสดงผลงานจริงตรงนี้)\n\nรับงานนี้ไหม?',
  'ask.deliver.ph': 'หรือบอกว่าอยากแก้อะไร',
  'ask.changeWhat': 'อยากให้แก้อะไร?',
  'ask.changeWhat.ph': 'บอกได้เลยว่าจะให้แก้อะไร',
};

export const STRINGS = { en, th } as const;
